language: r
sudo: required
dist: trusty
bioc_required: true
cache: packages
warnings_are_errors: true
addons:
  apt:
    packages:
      - libgsl-dev
      - libsdl1.2-dev
      - libreadline-dev
      - imagemagick
      - libfftw3-dev
      - libudunits2-dev
install:
 - R -e 'install.packages("devtools")'
 - R -e 'devtools::install(dependencies = TRUE, upgrade_dependencies = TRUE)'
 - R -e 'dynmethods::check_dependencies()'
 - "pip3 install --upgrade pip setuptools wheel"
 - "pip3 install --only-binary=numpy,scipy numpy scipy"
 - "pip3 install matplotlib pandas six jinja2 python-dateutil pytz pyparsing cycler tqdm python-igraph rpy2 Cython statsmodels sklearn seaborn"
