language: r
sudo: required
dist: trusty
bioc_required: true
cache: packages
warnings_are_errors: true
python:
  - "3.6"
addons:
  apt:
    packages:
      - libgsl-dev
      - libsdl1.2-dev
      - libreadline-dev
      - imagemagick
      - libfftw3-dev
      - libudunits2-dev
      - libblas-dev
      - liblapack-dev
before_install:
  - sudo apt-get -y install python3-pip
  - sudo pip3 install --upgrade pip setuptools wheel
  - python3 -V
  - pip3 -V
install:
  - sudo pip3 install --upgrade --only-binary=numpy,scipy numpy scipy
  - sudo pip3 install --upgrade matplotlib pandas six jinja2 python-dateutil pytz pyparsing cycler tqdm python-igraph Cython statsmodels sklearn seaborn
  - R -e 'install.packages("remotes")'
  - R -e 'remotes::install_deps(dependencies = T, upgrade = T)'
  - R -e 'remotes::install_local(".")'
  - R -e 'dynmethods::check_dependencies()'
